name:

image:
  name:
  tag:

nodeSelector:
  tier:

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

configmap:
  enabled: false

secret:
  enabled: false

podAnnotations:
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/agent-configmap: ''
  vault.hashicorp.com/template-static-secret-render-interval: "1m"
  vault.hashicorp.com/agent-run-as-user: '101'

tolerations: []

affinity: {}

ingress:
  enabled: false
  class: alb
  albName:
  hosts: []

hpa:
  minReplicas: 2
  maxReplicas: 20

containerPort: 3000

healthCheck: /api/stat

healthCheckTimeout: 10

command:

serviceAccountName: internal-app

vaultRole:

vaultPath:

vaultAgentConfigmap:

runAsUser: 1001

fsGroup: 1001